name: Release Workflow

on:
  release:
    types: [created]
    
jobs:
  deploy:
    DEBUG: true
    runs-on: ubuntu-latest
    
    steps:
    

    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Composer dependencies
      run: composer install --no-dev

    - name: Modify .env
      run: |
        sed -i 's/ENVIRONMENT = development/ENVIRONMENT = production/g' .env
        cat .env
        
    - name: Modify App.php
      run: |
        sed -i "s|\$baseURL = '.*';|\$baseURL = '${{ secrets.BASE_URL }}';|g" app/Config/App.php
        cat app/Config/App.php
      
    - name: Debug repository files
      run: ls -lR
      
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
